"""create perfume/note/m2m/user tables

Revision ID: 95333f1d8e6b
Revises: 4c5b421aedac
Create Date: 2025-11-03 16:45:25.749684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95333f1d8e6b'
down_revision: Union[str, Sequence[str], None] = '4c5b421aedac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('perfume',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('launch_year', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('na', 'unisex', 'men', 'women', name='gender'), server_default='na', nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('main_accords', sa.JSON(), nullable=True),
    sa.Column('rating_avg', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('longevity_avg', sa.Float(), nullable=True),
    sa.Column('sillage_avg', sa.Float(), nullable=True),
    sa.Column('concentration', sa.Enum('edt', 'edp', 'parfum', 'cologne', 'other', name='concentration'), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('external_source', sa.Enum('fragella', 'custom', name='externalsource'), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfume_external_id'), 'perfume', ['external_id'], unique=False)
    op.create_index('ix_perfume_source_extid', 'perfume', ['external_source', 'external_id'], unique=True)
    op.create_table('perfume_note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('perfume_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('top', 'middle', 'base', name='noterole'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('perfume_id', 'note_id', 'role', name='uq_perfume_note_role')
    )
    op.create_index(op.f('ix_perfume_note_note_id'), 'perfume_note', ['note_id'], unique=False)
    op.create_index(op.f('ix_perfume_note_perfume_id'), 'perfume_note', ['perfume_id'], unique=False)
    op.add_column('brand', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('brand', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand', 'updated_at')
    op.drop_column('brand', 'created_at')
    op.drop_index(op.f('ix_perfume_note_perfume_id'), table_name='perfume_note')
    op.drop_index(op.f('ix_perfume_note_note_id'), table_name='perfume_note')
    op.drop_table('perfume_note')
    op.drop_index('ix_perfume_source_extid', table_name='perfume')
    op.drop_index(op.f('ix_perfume_external_id'), table_name='perfume')
    op.drop_table('perfume')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('note')
    # ### end Alembic commands ###
