"""add revoked column

Revision ID: 1a17c6ab329d
Revises: 52fa5f0732dc
Create Date: 2025-11-22 12:18:10.752543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1a17c6ab329d'
down_revision: Union[str, Sequence[str], None] = '52fa5f0732dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pbti_question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('axis', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pbti_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BINARY(length=16), nullable=False),
    sa.Column('temperature_score', sa.Integer(), nullable=False),
    sa.Column('texture_score', sa.Integer(), nullable=False),
    sa.Column('mood_score', sa.Integer(), nullable=False),
    sa.Column('nature_score', sa.Integer(), nullable=False),
    sa.Column('final_type', sa.String(length=4), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.Column('answers', mysql.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pbti_result_user_id'), 'pbti_result', ['user_id'], unique=False)
    op.create_index('ix_pbti_user_active', 'pbti_result', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_wishlist_perfume_id'), 'wishlist', ['perfume_id'], unique=False)
    op.create_index('ix_wishlist_user', 'wishlist', ['user_id'], unique=False)
    op.create_index(op.f('ix_wishlist_user_id'), 'wishlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlist_user_id'), table_name='wishlist')
    op.drop_index('ix_wishlist_user', table_name='wishlist')
    op.drop_index(op.f('ix_wishlist_perfume_id'), table_name='wishlist')
    op.drop_index('ix_pbti_user_active', table_name='pbti_result')
    op.drop_index(op.f('ix_pbti_result_user_id'), table_name='pbti_result')
    op.drop_table('pbti_result')
    op.drop_table('pbti_question')
    # ### end Alembic commands ###
