"""refresh_token

Revision ID: 38b8ba9ecb9e
Revises: 50a4cd7cf8db
Create Date: 2025-11-23 21:50:21.836572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '38b8ba9ecb9e'
down_revision: Union[str, Sequence[str], None] = '50a4cd7cf8db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_token', 'token',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.drop_index(op.f('token'), table_name='refresh_token')
    op.create_index(op.f('ix_refresh_token_token'), 'refresh_token', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_token_token'), table_name='refresh_token')
    op.create_index(op.f('token'), 'refresh_token', ['token'], unique=True)
    op.alter_column('refresh_token', 'token',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
