"""add pbti scores to perfume model

Revision ID: 50a4cd7cf8db
Revises: 98d079e1f7c6
Create Date: 2025-11-23 19:27:36.016930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a4cd7cf8db'
down_revision: Union[str, Sequence[str], None] = '98d079e1f7c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfume', sa.Column('F_W_Score', sa.Float(), nullable=True))
    op.add_column('perfume', sa.Column('L_H_Score', sa.Float(), nullable=True))
    op.add_column('perfume', sa.Column('S_P_Score', sa.Float(), nullable=True))
    op.add_column('perfume', sa.Column('N_M_Score', sa.Float(), nullable=True))
    op.add_column('perfume', sa.Column('pbti_type', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfume', 'pbti_type')
    op.drop_column('perfume', 'N_M_Score')
    op.drop_column('perfume', 'S_P_Score')
    op.drop_column('perfume', 'L_H_Score')
    op.drop_column('perfume', 'F_W_Score')
    # ### end Alembic commands ###
