"""add fragella fields to perfume

Revision ID: 5e99561d2527
Revises: 413b748435cf
Create Date: 2025-11-10 19:49:25.154939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e99561d2527'
down_revision: Union[str, Sequence[str], None] = '413b748435cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfume', sa.Column('source_url', sa.String(length=255), nullable=True))
    op.add_column('perfume', sa.Column('concentration', sa.String(length=50), nullable=True))
    op.add_column('perfume', sa.Column('external_source', sa.String(length=50), nullable=False))
    op.add_column('perfume', sa.Column('external_id', sa.String(length=100), nullable=False))
    op.create_unique_constraint('uq_perfume_external', 'perfume', ['external_source', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_perfume_external', 'perfume', type_='unique')
    op.drop_column('perfume', 'external_id')
    op.drop_column('perfume', 'external_source')
    op.drop_column('perfume', 'concentration')
    op.drop_column('perfume', 'source_url')
    # ### end Alembic commands ###
