"""add pbti tables

Revision ID: 77a487a803b5
Revises: aec81abb98d9
Create Date: 2025-11-22 11:02:29.188406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '77a487a803b5'
down_revision: Union[str, Sequence[str], None] = 'aec81abb98d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pbti_question', sa.Column('axis', sa.String(length=20), nullable=False))
    op.add_column('pbti_question', sa.Column('direction', sa.Integer(), nullable=False))
    op.add_column('pbti_question', sa.Column('text', sa.Text(), nullable=False))
    op.drop_column('pbti_question', 'dimension')
    op.drop_column('pbti_question', 'question_text')
    op.add_column('pbti_result', sa.Column('temperature_score', sa.Integer(), nullable=True))
    op.add_column('pbti_result', sa.Column('texture_score', sa.Integer(), nullable=True))
    op.add_column('pbti_result', sa.Column('mood_score', sa.Integer(), nullable=True))
    op.add_column('pbti_result', sa.Column('nature_score', sa.Integer(), nullable=True))
    op.drop_column('pbti_result', 'dimension_1_score')
    op.drop_column('pbti_result', 'dimension_3_score')
    op.drop_column('pbti_result', 'dimension_2_score')
    op.drop_column('pbti_result', 'dimension_4_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pbti_result', sa.Column('dimension_4_score', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pbti_result', sa.Column('dimension_2_score', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pbti_result', sa.Column('dimension_3_score', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pbti_result', sa.Column('dimension_1_score', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pbti_result', 'nature_score')
    op.drop_column('pbti_result', 'mood_score')
    op.drop_column('pbti_result', 'texture_score')
    op.drop_column('pbti_result', 'temperature_score')
    op.add_column('pbti_question', sa.Column('question_text', mysql.TEXT(), nullable=False))
    op.add_column('pbti_question', sa.Column('dimension', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('pbti_question', 'text')
    op.drop_column('pbti_question', 'direction')
    op.drop_column('pbti_question', 'axis')
    # ### end Alembic commands ###
