"""add revoked column

Revision ID: 83e6302d123c
Revises: aec81abb98d9
Create Date: 2025-11-22 11:46:13.021664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '83e6302d123c'
down_revision: Union[str, Sequence[str], None] = 'aec81abb98d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pbti_question', sa.Column('dimension', sa.Integer(), nullable=False))
    op.add_column('pbti_question', sa.Column('question_text', sa.Text(), nullable=False))
    op.drop_column('pbti_question', 'text')
    op.drop_column('pbti_question', 'direction')
    op.drop_column('pbti_question', 'axis')
    op.add_column('pbti_result', sa.Column('dimension_1_score', sa.Integer(), nullable=True))
    op.add_column('pbti_result', sa.Column('dimension_2_score', sa.Integer(), nullable=True))
    op.add_column('pbti_result', sa.Column('dimension_3_score', sa.Integer(), nullable=True))
    op.add_column('pbti_result', sa.Column('dimension_4_score', sa.Integer(), nullable=True))
    op.drop_column('pbti_result', 'temperature_score')
    op.drop_column('pbti_result', 'texture_score')
    op.drop_column('pbti_result', 'nature_score')
    op.drop_column('pbti_result', 'mood_score')
    op.add_column('refresh_token', sa.Column('revoked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_token', 'revoked')
    op.add_column('pbti_result', sa.Column('mood_score', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pbti_result', sa.Column('nature_score', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pbti_result', sa.Column('texture_score', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pbti_result', sa.Column('temperature_score', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pbti_result', 'dimension_4_score')
    op.drop_column('pbti_result', 'dimension_3_score')
    op.drop_column('pbti_result', 'dimension_2_score')
    op.drop_column('pbti_result', 'dimension_1_score')
    op.add_column('pbti_question', sa.Column('axis', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('pbti_question', sa.Column('direction', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pbti_question', sa.Column('text', mysql.TEXT(), nullable=False))
    op.drop_column('pbti_question', 'question_text')
    op.drop_column('pbti_question', 'dimension')
    # ### end Alembic commands ###
