"""fix pbti_question axis type

Revision ID: 98d079e1f7c6
Revises: ddcf32e6cfbb
Create Date: 2025-11-23 02:27:54.137163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '98d079e1f7c6'
down_revision: Union[str, Sequence[str], None] = 'ddcf32e6cfbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pbti_question', 'axis',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pbti_question', 'axis',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
