"""add wishlist and recent_view

Revision ID: 9d2ef8dbb2bc
Revises: c94db4c40b56
Create Date: 2025-11-11 18:00:57.550453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2ef8dbb2bc'
down_revision: Union[str, Sequence[str], None] = 'c94db4c40b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
