"""init schema (final reboot)

Revision ID: a5ae8dde2550
Revises: 
Create Date: 2025-11-07 09:43:40.460567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ae8dde2550'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_id'), 'brand', ['id'], unique=False)
    op.create_index(op.f('ix_brand_name'), 'brand', ['name'], unique=True)
    op.create_table('note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('perfume',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('brand_id', sa.BINARY(length=16), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('image_fallbacks', sa.JSON(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('fragella_id', sa.String(length=100), nullable=True),
    sa.Column('purchase_url', sa.String(length=255), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('longevity', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('sillage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('main_accords', sa.JSON(), nullable=True),
    sa.Column('main_accords_percentage', sa.JSON(), nullable=True),
    sa.Column('top_notes', sa.JSON(), nullable=True),
    sa.Column('middle_notes', sa.JSON(), nullable=True),
    sa.Column('base_notes', sa.JSON(), nullable=True),
    sa.Column('general_notes', sa.JSON(), nullable=True),
    sa.Column('season_ranking', sa.JSON(), nullable=True),
    sa.Column('occasion_ranking', sa.JSON(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('wish_count', sa.Integer(), nullable=True),
    sa.Column('purchase_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_synced_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fragella_id')
    )
    op.create_index(op.f('ix_perfume_brand_id'), 'perfume', ['brand_id'], unique=False)
    op.create_index(op.f('ix_perfume_id'), 'perfume', ['id'], unique=False)
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_refresh_expires', 'refresh_token', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.create_index('ix_refresh_user', 'refresh_token', ['user_id'], unique=False)
    op.create_table('perfume_calendar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('perfume_id', sa.BINARY(length=16), nullable=False),
    sa.Column('wear_date', sa.Date(), nullable=False),
    sa.Column('situation', sa.String(length=50), nullable=True),
    sa.Column('weather', sa.String(length=50), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'wear_date', 'perfume_id', name='uq_calendar_user_date_perfume')
    )
    op.create_index('ix_calendar_perfume', 'perfume_calendar', ['perfume_id'], unique=False)
    op.create_index('ix_calendar_user_date', 'perfume_calendar', ['user_id', 'wear_date'], unique=False)
    op.create_index(op.f('ix_perfume_calendar_perfume_id'), 'perfume_calendar', ['perfume_id'], unique=False)
    op.create_index(op.f('ix_perfume_calendar_user_id'), 'perfume_calendar', ['user_id'], unique=False)
    op.create_table('perfume_note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('perfume_id', sa.BINARY(length=16), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('top', 'middle', 'base', name='noterole'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('perfume_id', 'note_id', 'role', name='uq_perfume_note_role')
    )
    op.create_index(op.f('ix_perfume_note_note_id'), 'perfume_note', ['note_id'], unique=False)
    op.create_index(op.f('ix_perfume_note_perfume_id'), 'perfume_note', ['perfume_id'], unique=False)
    op.create_table('purchase_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('perfume_id', sa.BINARY(length=16), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_history_perfume_id'), 'purchase_history', ['perfume_id'], unique=False)
    op.create_index(op.f('ix_purchase_history_user_id'), 'purchase_history', ['user_id'], unique=False)
    op.create_index('ix_purchase_perfume', 'purchase_history', ['perfume_id'], unique=False)
    op.create_index('ix_purchase_user_date', 'purchase_history', ['user_id', 'purchase_date'], unique=False)
    op.create_table('recent_view',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('perfume_id', sa.BINARY(length=16), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'perfume_id', name='uq_recent_user_perfume')
    )
    op.create_index('ix_recent_user_viewed_at', 'recent_view', ['user_id', 'viewed_at'], unique=False)
    op.create_index(op.f('ix_recent_view_perfume_id'), 'recent_view', ['perfume_id'], unique=False)
    op.create_index(op.f('ix_recent_view_user_id'), 'recent_view', ['user_id'], unique=False)
    op.create_index(op.f('ix_recent_view_viewed_at'), 'recent_view', ['viewed_at'], unique=False)
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('perfume_id', sa.BINARY(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'perfume_id', name='uq_wishlist_user_perfume')
    )
    op.create_index('ix_wishlist_perfume', 'wishlist', ['perfume_id'], unique=False)
    op.create_index(op.f('ix_wishlist_perfume_id'), 'wishlist', ['perfume_id'], unique=False)
    op.create_index('ix_wishlist_user', 'wishlist', ['user_id'], unique=False)
    op.create_index(op.f('ix_wishlist_user_id'), 'wishlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlist_user_id'), table_name='wishlist')
    op.drop_index('ix_wishlist_user', table_name='wishlist')
    op.drop_index(op.f('ix_wishlist_perfume_id'), table_name='wishlist')
    op.drop_index('ix_wishlist_perfume', table_name='wishlist')
    op.drop_table('wishlist')
    op.drop_index(op.f('ix_recent_view_viewed_at'), table_name='recent_view')
    op.drop_index(op.f('ix_recent_view_user_id'), table_name='recent_view')
    op.drop_index(op.f('ix_recent_view_perfume_id'), table_name='recent_view')
    op.drop_index('ix_recent_user_viewed_at', table_name='recent_view')
    op.drop_table('recent_view')
    op.drop_index('ix_purchase_user_date', table_name='purchase_history')
    op.drop_index('ix_purchase_perfume', table_name='purchase_history')
    op.drop_index(op.f('ix_purchase_history_user_id'), table_name='purchase_history')
    op.drop_index(op.f('ix_purchase_history_perfume_id'), table_name='purchase_history')
    op.drop_table('purchase_history')
    op.drop_index(op.f('ix_perfume_note_perfume_id'), table_name='perfume_note')
    op.drop_index(op.f('ix_perfume_note_note_id'), table_name='perfume_note')
    op.drop_table('perfume_note')
    op.drop_index(op.f('ix_perfume_calendar_user_id'), table_name='perfume_calendar')
    op.drop_index(op.f('ix_perfume_calendar_perfume_id'), table_name='perfume_calendar')
    op.drop_index('ix_calendar_user_date', table_name='perfume_calendar')
    op.drop_index('ix_calendar_perfume', table_name='perfume_calendar')
    op.drop_table('perfume_calendar')
    op.drop_index('ix_refresh_user', table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_index('ix_refresh_expires', table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_perfume_id'), table_name='perfume')
    op.drop_index(op.f('ix_perfume_brand_id'), table_name='perfume')
    op.drop_table('perfume')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('note')
    op.drop_index(op.f('ix_brand_name'), table_name='brand')
    op.drop_index(op.f('ix_brand_id'), table_name='brand')
    op.drop_table('brand')
    # ### end Alembic commands ###
