"""recreate user as BINARY(16) and drop/rebuild deps

Revision ID: aec81abb98d9
Revises: 9d2ef8dbb2bc
Create Date: 2025-11-11 21:42:20.201336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aec81abb98d9'
down_revision: Union[str, Sequence[str], None] = '9d2ef8dbb2bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.create_table('user',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('pbti_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BINARY(length=16), nullable=False),
    sa.Column('dimension_1_score', sa.Integer(), nullable=True),
    sa.Column('dimension_2_score', sa.Integer(), nullable=True),
    sa.Column('dimension_3_score', sa.Integer(), nullable=True),
    sa.Column('dimension_4_score', sa.Integer(), nullable=True),
    sa.Column('final_type', sa.String(length=4), nullable=True),
    sa.Column('type_name', sa.String(length=50), nullable=True),
    sa.Column('answers', mysql.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pbti_result_user_id'), 'pbti_result', ['user_id'], unique=False)
    op.create_index('ix_pbti_user_active', 'pbti_result', ['user_id', 'is_active'], unique=False)
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BINARY(length=16), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_refresh_expires', 'refresh_token', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.create_index('ix_refresh_user', 'refresh_token', ['user_id'], unique=False)
    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BINARY(length=16), nullable=False),
    sa.Column('preferred_accords', mysql.JSON(), nullable=True),
    sa.Column('preferred_brands', mysql.JSON(), nullable=True),
    sa.Column('price_range_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_range_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preferred_seasons', mysql.JSON(), nullable=True),
    sa.Column('preferred_occasions', mysql.JSON(), nullable=True),
    sa.Column('last_calculated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_preference_user')
    )
    op.create_index('ix_user_pref_user', 'user_preference', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_preference_user_id'), 'user_preference', ['user_id'], unique=False)
    op.create_table('image_recognition_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BINARY(length=16), nullable=True),
    sa.Column('recognized_perfume_id', sa.BINARY(length=16), nullable=True),
    sa.Column('actual_perfume_id', sa.BINARY(length=16), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('candidate_perfumes', mysql.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actual_perfume_id'], ['perfume.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recognized_perfume_id'], ['perfume.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recog_model', 'image_recognition_log', ['model_version'], unique=False)
    op.create_index('ix_recog_user', 'image_recognition_log', ['user_id'], unique=False)
    op.create_table('perfume_calendar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BINARY(length=16), nullable=False),
    sa.Column('perfume_id', sa.BINARY(length=16), nullable=False),
    sa.Column('wear_date', sa.Date(), nullable=False),
    sa.Column('situation', sa.String(length=50), nullable=True),
    sa.Column('weather', sa.String(length=50), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'wear_date', 'perfume_id', name='uq_calendar_user_date_perfume')
    )
    op.create_index('ix_calendar_perfume', 'perfume_calendar', ['perfume_id'], unique=False)
    op.create_index('ix_calendar_user_date', 'perfume_calendar', ['user_id', 'wear_date'], unique=False)
    op.create_index(op.f('ix_perfume_calendar_perfume_id'), 'perfume_calendar', ['perfume_id'], unique=False)
    op.create_index(op.f('ix_perfume_calendar_user_id'), 'perfume_calendar', ['user_id'], unique=False)
    op.create_table('perfume_recommendation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BINARY(length=16), nullable=False),
    sa.Column('perfume_id', sa.BINARY(length=16), nullable=False),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('was_viewed', sa.Boolean(), nullable=False),
    sa.Column('was_clicked', sa.Boolean(), nullable=False),
    sa.Column('was_added_to_wishlist', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfume_recommendation_perfume_id'), 'perfume_recommendation', ['perfume_id'], unique=False)
    op.create_index(op.f('ix_perfume_recommendation_user_id'), 'perfume_recommendation', ['user_id'], unique=False)
    op.create_index('ix_reco_perfume', 'perfume_recommendation', ['perfume_id'], unique=False)
    op.create_index('ix_reco_user_type_score', 'perfume_recommendation', ['user_id', 'recommendation_type', 'score'], unique=False)
    op.create_table('purchase_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BINARY(length=16), nullable=False),
    sa.Column('perfume_id', sa.BINARY(length=16), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_history_perfume_id'), 'purchase_history', ['perfume_id'], unique=False)
    op.create_index(op.f('ix_purchase_history_user_id'), 'purchase_history', ['user_id'], unique=False)
    op.create_index('ix_purchase_perfume', 'purchase_history', ['perfume_id'], unique=False)
    op.create_index('ix_purchase_user_date', 'purchase_history', ['user_id', 'purchase_date'], unique=False)
    op.create_table('recent_view',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BINARY(length=16), nullable=False),
    sa.Column('perfume_id', sa.BINARY(length=16), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'perfume_id', name='uq_recent_user_perfume')
    )
    op.create_index('ix_recent_user_viewed_at', 'recent_view', ['user_id', 'viewed_at'], unique=False)
    op.create_index(op.f('ix_recent_view_perfume_id'), 'recent_view', ['perfume_id'], unique=False)
    op.create_index(op.f('ix_recent_view_user_id'), 'recent_view', ['user_id'], unique=False)
    op.create_index(op.f('ix_recent_view_viewed_at'), 'recent_view', ['viewed_at'], unique=False)
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BINARY(length=16), nullable=False),
    sa.Column('perfume_id', sa.BINARY(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'perfume_id', name='uq_wishlist_user_perfume')
    )
    op.create_index('ix_wishlist_perfume', 'wishlist', ['perfume_id'], unique=False)
    op.create_index(op.f('ix_wishlist_perfume_id'), 'wishlist', ['perfume_id'], unique=False)
    op.create_index('ix_wishlist_user', 'wishlist', ['user_id'], unique=False)
    op.create_index(op.f('ix_wishlist_user_id'), 'wishlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlist_user_id'), table_name='wishlist')
    op.drop_index('ix_wishlist_user', table_name='wishlist')
    op.drop_index(op.f('ix_wishlist_perfume_id'), table_name='wishlist')
    op.drop_index('ix_wishlist_perfume', table_name='wishlist')
    op.drop_table('wishlist')
    op.drop_index(op.f('ix_recent_view_viewed_at'), table_name='recent_view')
    op.drop_index(op.f('ix_recent_view_user_id'), table_name='recent_view')
    op.drop_index(op.f('ix_recent_view_perfume_id'), table_name='recent_view')
    op.drop_index('ix_recent_user_viewed_at', table_name='recent_view')
    op.drop_table('recent_view')
    op.drop_index('ix_purchase_user_date', table_name='purchase_history')
    op.drop_index('ix_purchase_perfume', table_name='purchase_history')
    op.drop_index(op.f('ix_purchase_history_user_id'), table_name='purchase_history')
    op.drop_index(op.f('ix_purchase_history_perfume_id'), table_name='purchase_history')
    op.drop_table('purchase_history')
    op.drop_index('ix_reco_user_type_score', table_name='perfume_recommendation')
    op.drop_index('ix_reco_perfume', table_name='perfume_recommendation')
    op.drop_index(op.f('ix_perfume_recommendation_user_id'), table_name='perfume_recommendation')
    op.drop_index(op.f('ix_perfume_recommendation_perfume_id'), table_name='perfume_recommendation')
    op.drop_table('perfume_recommendation')
    op.drop_index(op.f('ix_perfume_calendar_user_id'), table_name='perfume_calendar')
    op.drop_index(op.f('ix_perfume_calendar_perfume_id'), table_name='perfume_calendar')
    op.drop_index('ix_calendar_user_date', table_name='perfume_calendar')
    op.drop_index('ix_calendar_perfume', table_name='perfume_calendar')
    op.drop_table('perfume_calendar')
    op.drop_index('ix_recog_user', table_name='image_recognition_log')
    op.drop_index('ix_recog_model', table_name='image_recognition_log')
    op.drop_table('image_recognition_log')
    op.drop_index(op.f('ix_user_preference_user_id'), table_name='user_preference')
    op.drop_index('ix_user_pref_user', table_name='user_preference')
    op.drop_table('user_preference')
    op.drop_index('ix_refresh_user', table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_index('ix_refresh_expires', table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index('ix_pbti_user_active', table_name='pbti_result')
    op.drop_index(op.f('ix_pbti_result_user_id'), table_name='pbti_result')
    op.drop_table('pbti_result')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
