"""increase purchase_url length to Text

Revision ID: c94db4c40b56
Revises: 5e99561d2527
Create Date: 2025-11-10 21:46:05.262259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c94db4c40b56'
down_revision: Union[str, Sequence[str], None] = '5e99561d2527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_unique_constraint('uq_brand_name', 'brand', ['name'])
    op.alter_column('perfume', 'purchase_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('perfume', 'purchase_url',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint('uq_brand_name', 'brand', type_='unique')
    # ### end Alembic commands ###
