"""Update refresh_token user_id to BINARY(16)

Revision ID: d1da20a45582
Revises: f9b5ff9fcaf7
Create Date: 2025-11-23 00:13:15.163379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd1da20a45582'
down_revision: Union[str, Sequence[str], None] = 'f9b5ff9fcaf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_pbti_recommendation_type_code'), table_name='pbti_recommendation')
    op.drop_table('pbti_recommendation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pbti_recommendation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('perfume_id', sa.BINARY(length=16), nullable=False),
    sa.Column('match_score', mysql.FLOAT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], name=op.f('pbti_recommendation_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_pbti_recommendation_type_code'), 'pbti_recommendation', ['type_code'], unique=False)
    op.create_index(op.f('ix_pbti_recommendation_perfume_id'), 'pbti_recommendation', ['perfume_id'], unique=False)
    # ### end Alembic commands ###
