"""add accord + perfume_accord + monthly/seasonal + image_recognition

Revision ID: d224909cf530
Revises: 8a2a56c6fde5
Create Date: 2025-11-07 10:05:30.417921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd224909cf530'
down_revision: Union[str, Sequence[str], None] = '8a2a56c6fde5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('name_korean', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurrence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('seasonal_recommendation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('perfume_ids', mysql.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_recognition_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recognized_perfume_id', sa.BINARY(length=16), nullable=True),
    sa.Column('actual_perfume_id', sa.BINARY(length=16), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('candidate_perfumes', mysql.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actual_perfume_id'], ['perfume.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recognized_perfume_id'], ['perfume.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recog_model', 'image_recognition_log', ['model_version'], unique=False)
    op.create_index('ix_recog_user', 'image_recognition_log', ['user_id'], unique=False)
    op.create_table('monthly_perfume',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('perfume_id', sa.BINARY(length=16), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('perfume_id', 'year', 'month', name='uq_monthly_perfume_year_month')
    )
    op.create_index('ix_monthly_perfume_year_month', 'monthly_perfume', ['year', 'month'], unique=False)
    op.create_table('perfume_accord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('perfume_id', sa.BINARY(length=16), nullable=False),
    sa.Column('accord_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accord_id'], ['accord.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfume.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('perfume_id', 'accord_id', name='uq_perfume_accord')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perfume_accord')
    op.drop_index('ix_monthly_perfume_year_month', table_name='monthly_perfume')
    op.drop_table('monthly_perfume')
    op.drop_index('ix_recog_user', table_name='image_recognition_log')
    op.drop_index('ix_recog_model', table_name='image_recognition_log')
    op.drop_table('image_recognition_log')
    op.drop_table('seasonal_recommendation')
    op.drop_table('accord')
    # ### end Alembic commands ###
